INSERT INTO projetos_escola (escola_id, serie, envio_1, envio_2, envio_3) VALUES
  ('maple-bear-itabira', '1º ano', 'Rodopios', 'Dinossauros', 'Os Três Porquinhos'),
  ('maple-bear-itabira', '2º ano', 'Cola quente', NULL, NULL),
  ('maple-bear-itabira', '2° ano', 'Nascer do Sol', 'Medalhões', 'Bichinhos de Jardim'),
  ('maple-bear-itabira', '3° ano', 'Cola quente', NULL, NULL),
  ('maple-bear-itabira', '3º ano', 'Choveu na minha Escola', 'Telégrafo', 'Borbulhas'),
  ('maple-bear-itabira', '4º ano', 'Como isso chegou aí?', 'Navegadores', 'Locomotiva'),
  ('maple-bear-itabira', '5º ano', 'Nossa água', 'Cozinha Maker', 'Cinema'),
  ('master', '1º ano', 'Rodopios', NULL, 'O Canto do Passarinho'),
  ('master', '2º ano', 'Nascer do Sol', NULL, 'Bichinhos de Jardim'),
  ('master', '3º ano', 'Choveu na minha Escola', NULL, 'Borbulhas'),
  ('master', '4º ano', 'Como isso chegou aí?', NULL, 'Telégrafo'),
  ('master', '5º ano', 'Nossa Água', NULL, 'Cozinha Maker'),
  ('master', '6º ano', 'Sobrevoo', NULL, 'Através da Lente'),
  ('master', '7º ano', 'Teatro Robótico', NULL, 'Reinventando as Horas'),
  ('master', '8º ano', 'Criasom', NULL, 'Enigma'),
  ('master', '9º ano', 'Brilhantemente', NULL, 'Comunicamão'),
  ('parthenon', '6º ano', 'Sobrevoo', NULL, 'Assumindo o Controle'),
  ('parthenon', '7º ano', 'Tempos Modernos', NULL, 'Reinventando as Horas'),
  ('parthenon', '8º ano', 'Criasom', NULL, 'Enigma'),
  ('parthenon', '9º ano', 'Brilhantemente', NULL, 'Robotrônico'),
  ('passos-firmes', '1º ano', 'Rodopios', 'Dinossauros', 'Os Três Porquinhos'),
  ('passos-firmes', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('passos-firmes', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('passos-firmes', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('passos-firmes', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('passos-firmes', '1º ano EM', 'Nossa Água', 'Cozinha Maker', 'Cozinha Maker'),
  ('passos-firmes', '2º ano EM', 'Sobrevoo', 'Através da Lente', 'Através da lente'),
  ('ph-barra', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-barra', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-barra', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-barra', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-barra', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-barra', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-barra', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-barra', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-barra', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-botafogo-i', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-botafogo-i', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-botafogo-i', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-botafogo-i', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-botafogo-i', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-botafogo-ii', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-botafogo-ii', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-botafogo-ii', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-botafogo-ii', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-freguesia', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-freguesia', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-freguesia', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-freguesia', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-freguesia', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-freguesia', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-freguesia', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-freguesia', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-freguesia', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-icarai-ii', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-icarai-ii', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-icarai-ii', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-icarai-iii', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-icarai-iii', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-icarai-iii', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-icarai-iii', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-icarai-iii', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-icarai-iii', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-icarai-iii', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-icarai-iii', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-icarai-iii', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-ilha-pura', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-ilha-pura', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-ilha-pura', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-ilha-pura', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-ilha-pura', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-ilha-pura', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-ilha-pura', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-ilha-pura', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-ilha-pura', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-jockey', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-jockey', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-jockey', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-jockey', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-jockey', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-jockey', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-jockey', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-jockey', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-jockey', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-piratininga', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-piratininga', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-piratininga', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-piratininga', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-recreio', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-recreio', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-recreio', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-recreio', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-recreio', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-recreio', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-recreio', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-recreio', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-recreio', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('ph-tijuca', '1º ano', 'Toolmates', 'Three Maker Piggies', 'Fossil Hunters'),
  ('ph-tijuca', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('ph-tijuca', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('ph-tijuca', '4º ano', 'Around the world', 'All Board', 'Sea Explorers'),
  ('ph-tijuca', '5º ano', 'Make &  Bake', 'Sustainable me', 'Cinemakers'),
  ('ph-tijuca', '6º ano', 'Sobrevoo', 'Através da Lente', 'Assumindo o Controle'),
  ('ph-tijuca', '7º ano', 'Tempos Modernos', 'Teatro Robótico', 'Reinventando as Horas'),
  ('ph-tijuca', '8º ano', 'Criasom', 'Tá na vez de quem?', 'Enigma'),
  ('ph-tijuca', '9º ano', 'Brilhantemente', 'Comunicamão', 'Robotrônico'),
  ('shunji-nishimura', 'EI', 'O Canto do Passarinho', 'Casarão Abandonado', 'Casinha de ferramentas'),
  ('shunji-nishimura', '1º ano', 'Rodopios', 'Dinossauros', 'Os Três Porquinhos'),
  ('shunji-nishimura', '2º ano', 'Nascer do Sol', 'Medalhões', 'Bichinhos de Jardim'),
  ('shunji-nishimura', '3º ano', 'Choveu na minha Escola', 'Telégrafo', 'Borbulhas'),
  ('shunji-nishimura', '4º ano', 'Como isso chegou aí?', 'Navegadores', 'Locomotiva'),
  ('shunji-nishimura', '5º ano', 'Nossa água', 'Cozinha Maker', 'Cinema'),
  ('step-by-step', '1º ano', 'Rodopios', 'Dinossauros', 'Os Três Porquinhos'),
  ('step-by-step', '2º ano', 'Nascer do Sol', 'Medalhões', 'Bichinhos de Jardim'),
  ('trails-school', '1º ano', 'Old is cool', 'Fossil Hunters', 'Three Maker Piggies'),
  ('trails-school', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('trails-school', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('trails-school', '4º ano', 'Around the world', 'Sea Explorers', 'All aboard!')
ON CONFLICT (escola_id, serie) DO UPDATE SET envio_1 = EXCLUDED.envio_1, envio_2 = EXCLUDED.envio_2, envio_3 = EXCLUDED.envio_3;
