INSERT INTO projetos_escola (escola_id, serie, envio_1, envio_2, envio_3) VALUES
  ('albertino-goncalves', '1º ano', 'Rodopios', NULL, 'Três Porquinhos'),
  ('albertino-goncalves', '2º ano', 'Nascer do sol', NULL, 'Bichinhos de Jardim'),
  ('albertino-goncalves', '3º ano', 'Choveu na minha escola', NULL, 'Borbulhas'),
  ('albertino-goncalves', '4º ano', 'Como isso chegou ai?', NULL, 'Locomotiva'),
  ('albertino-goncalves', '5º ano', 'Nossa água', NULL, 'Cinema'),
  ('albertino-goncalves', '6º ano', 'Sobrevoo', NULL, 'Assumindo o controle'),
  ('albertino-goncalves', '7º ano', 'Tempos modernos', NULL, 'Reiventando as horas'),
  ('albertino-goncalves', '8º ano', 'Criasom', NULL, 'Enigma'),
  ('albertino-goncalves', '9º ano', 'Brilhante[mente]', NULL, 'Robotronico'),
  ('agostiniano-mendel', 'EI', 'A ilha mágica', NULL, 'Casarão Abandonado'),
  ('agostiniano-mendel', '1º ano', 'Três Porquinhos', NULL, 'Dinossauros'),
  ('agostiniano-mendel', '2º ano', 'Bichinhos de Jardim', NULL, 'Medalhões'),
  ('agostiniano-mendel', '3º ano', 'Borbulhas', NULL, 'Telégrafo'),
  ('agostiniano-mendel', '4º ano', 'Locomotiva', NULL, 'Navegadores'),
  ('agostiniano-mendel', '5º ano', 'Cinema', NULL, 'Cozinha Maker'),
  ('agostiniano-sao-jose', '6º ano', 'Jornada do Herói', NULL, 'Anime-se'),
  ('agostiniano-sao-jose', '7º ano', 'Rumo a Marte', NULL, 'Cidade em Movimento'),
  ('agostiniano-sao-jose', '9º ano', 'Avatar', NULL, 'Qual é sua ideIA?'),
  ('arqui', '1º ano', 'Três Porquinhos', NULL, 'Rodopios'),
  ('arqui', '2º ano', 'Bichinhos do Jardim', NULL, 'Nascer do Sol'),
  ('arqui', '3º ano', 'Borbulhas', NULL, 'Choveu na minha escola'),
  ('arqui', '4º ano', 'Locomotiva', NULL, 'Como isso Chegou ai?'),
  ('arqui', '5º ano', 'Cinema', NULL, 'Cozinha Maker'),
  ('arqui', '6º ano', 'Assumindo o controle', NULL, 'Sobrevoo'),
  ('arqui', '7º ano', 'Reiventando as horas', NULL, 'Tempos modernos'),
  ('arqui', '8º ano', 'Enigma', NULL, 'Criasom'),
  ('arqui', '9º ano', 'Robotronico', NULL, 'Comunicamão'),
  ('atitude', 'EI', 'O Canto do Passarinho', NULL, 'Casarão Abandonado'),
  ('atitude', '1º ano', 'Rodopios', NULL, 'Dinossauros'),
  ('atitude', '2º ano', 'Nascer do Sol', NULL, 'Medalhões'),
  ('atitude', '3º ano', 'Choveu na minha Escola', NULL, 'Telegrafo'),
  ('atitude', '4º ano', 'Como isso chegou aí?', NULL, 'Navegadores'),
  ('atitude', '5º ano', 'Nossa Água', NULL, 'Cozinha Maker'),
  ('atitude', '6º ano', 'Sobrevoo', NULL, 'Assumindo o Controle'),
  ('atitude', '7º ano', 'Tempos Modernos', NULL, 'Teatro robotico'),
  ('atitude', '8º ano', 'Criasom', NULL, 'Ta na vez de quem ?'),
  ('atitude', '9º ano', 'Brilhantemente', NULL, 'Comunicamão'),
  ('atitude', '1º ano EM', 'Robotronico', NULL, 'Reiventando as horas'),
  ('aubrick', '6º ano', 'Sustainable me', NULL, 'Gaining Control'),
  ('aubrick', '7º ano', 'Fly away', NULL, 'Time after Time'),
  ('aubrick', '8º ano', 'Modern Times', NULL, 'Enigmaker'),
  ('belo-futuro', '6º ano', 'Sobrevoo', NULL, 'Assumindo o Controle'),
  ('belo-futuro', '7º ano', 'Tempos modernos', 'Teatro Robótico', NULL),
  ('belo-futuro', '8º ano', 'Criasom', NULL, 'Enigma'),
  ('belo-futuro', '9º ano', NULL, 'Comunicamão', 'Robotronico'),
  ('bis', '2º ano', 'Here comes the sun', NULL, 'Is there anybody home?'),
  ('bis', '3º ano', 'Blowing Bubbles', NULL, 'Three Maker Piggies'),
  ('bis', '4º ano', 'Around the world', NULL, 'All Aboard'),
  ('bis', '5º ano', 'Sustainable me', NULL, 'Cinemakers'),
  ('bis', '6º ano', 'Fly away', NULL, 'Gaining control'),
  ('bis', '7º ano', 'Modern Times', NULL, 'StoryBot'),
  ('bis', '8º ano', 'Hitmaker', NULL, 'Lend a hand'),
  ('brasil-canada-perdizes', '1º ano', 'Fossil hunters', NULL, 'Three Maker Piggies'),
  ('brasil-canada-perdizes', '2º ano', 'Here comes the sun', NULL, 'Backyard Critters'),
  ('brasil-canada-perdizes', '3º ano', 'Weather Craft', NULL, 'Blowing bubbles'),
  ('brasil-canada-perdizes', '4º ano', 'Around the world', NULL, 'All Aboard'),
  ('brasil-canada-perdizes', '5º ano', 'Sustainable me', NULL, 'Cinemaker'),
  ('brasil-canada-perdizes', '6º ano', 'Fly away', NULL, 'Gaining control'),
  ('brasil-canada-perdizes', '7º ano', 'Modern Times', NULL, 'Time after Time'),
  ('brasil-canada-perdizes', '8º ano', 'Hitmaker', NULL, 'Enigmaker'),
  ('brasil-canada-perdizes', '9º ano', 'Bright Ideas', NULL, 'A-Droid'),
  ('brasil-canada-santana', 'EI', 'Birdie Buddy', NULL, 'Toolmates'),
  ('brasil-canada-santana', '1º ano', 'Old is cool', NULL, 'Three Maker Piggies'),
  ('brasil-canada-santana', '2º ano', 'Here comes the sun', NULL, 'Backyard Critters'),
  ('brasilia', '5º ano', 'Nossa Água', 'Cozinha Maker', NULL),
  ('brasilia', '6º ano', 'Sobrevoo', 'Através da lente', NULL),
  ('brasilia', '7º ano', 'Tempos Modernos', 'Teatro Robótico', NULL),
  ('brasilia', '8º ano', 'Criasom', 'Tá na vez de quem?', NULL),
  ('brasilia', '9º ano', 'Brilhantemente', 'Comunicamão', NULL),
  ('cel-lep', 'EI', 'Birdie Buddy', NULL, NULL),
  ('cel-lep', '1º ano', 'Old is cool', NULL, NULL),
  ('cel-lep', '5º ano', 'Cinemaker', NULL, NULL),
  ('cel-lep', '8º ano', 'Electric circuits', NULL, NULL),
  ('dominus-vivendi', 'EI', 'O Canto do Passarinho', 'Casarão Abandonado', NULL),
  ('dominus-vivendi', '1º ano', 'Rodopios', 'Dinossauros', NULL),
  ('dominus-vivendi', '2º ano', 'Nascer do Sol', 'Medalhões', NULL),
  ('dominus-vivendi', '3º ano', 'Choveu na minha Escola', 'Telégrafo', NULL),
  ('dominus-vivendi', '4º ano', 'Como isso chegou aí?', 'Navegadores', NULL),
  ('dominus-vivendi', '5º ano', 'Nossa Água', 'Cozinha Maker', NULL),
  ('dominus-vivendi', '6º ano', 'Sobrevoo', 'Através da Lente', NULL),
  ('dominus-vivendi', '7º ano', 'Tempos Modernos', 'Teatro Robótico', NULL),
  ('dominus-vivendi', '8º ano', 'Criasom', 'Tá na vez de quem?', NULL),
  ('dominus-vivendi', '9º ano', 'Brilhantemente', 'Comunicamão', NULL),
  ('esc-olaria-ii', '1º ano', 'Rodopios', NULL, 'Três Porquinhos'),
  ('esc-olaria-i', '2º ano', 'Nascer do Sol', NULL, 'Bichinhos de Jardim'),
  ('esc-olaria-i', '3º ano', 'Choveu na minha Escola', NULL, 'Borbulhas'),
  ('esc-olaria-i', '4º ano', 'Como isso chegou aí?', NULL, 'Locomotiva'),
  ('esc-olaria-i', '5º ano', 'Nossa Água', NULL, 'Cinemaker'),
  ('esc-recreio', '1º ano', 'Rodopios', NULL, 'Três Porquinhos'),
  ('esc-recreio', '2º ano', 'Nascer do Sol', NULL, 'Bichinhos de Jardim'),
  ('esc-recreio', '4º ano', 'Como isso chegou aí?', NULL, 'Locomotiva'),
  ('lyceu', '8º ano', 'Nossa Água', NULL, 'Cozinha Maker'),
  ('lyceu', '9º ano', 'Sobrevoo', NULL, 'Através da Lente'),
  ('lyceu', '1º ano EM', 'Tempos Modernos', NULL, 'Teatro Robótico'),
  ('lyceu', '2º ano EM', 'Criasom', NULL, 'Ta na vez de quem ?'),
  ('lyceu', '3º ano EM', 'Brilhantemente', NULL, 'Comunicamão'),
  ('maple-bear-marilia', '1º ano (Full Time 2)', 'Old is cool', 'Three Maker Piggies', 'Here comes the sun'),
  ('maple-bear-marilia', '2º ano (Full Time 3)', 'Backyard''s critters', 'Toolmates', 'Weather Craft'),
  ('maple-bear-marilia', '3º ano (Club Maker SK - Y2)', 'Blowing Bubbles', 'Here comes the sun', 'Is there anybody home?'),
  ('maple-bear-marilia', '5º ano (Club Maker Y3 -Y5)', 'Make & Bake', 'Sustainable me', 'Cinemakers'),
  ('maple-bear-marilia', '6º ano', 'Gaining Control', 'Fly Away', 'Light, camera, action!'),
  ('maple-bear-marilia', '7º ano', 'Modern Times', 'StoryBot', 'Time after Time'),
  ('maple-bear-marilia', '8º ano', 'Hitmaker', 'Game Designers', 'Enigmaker'),
  ('maple-bear-mogi', '2° ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('maple-bear-mogi', '4° ano', 'Around the world', 'Sea Explorers', 'All aboard!'),
  ('maple-bear-morumbi', '1º ano', 'Old is cool', 'Fossil Hunters', 'Three Maker Piggies'),
  ('maple-bear-morumbi', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('maple-bear-morumbi', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('maple-bear-morumbi', '5º ano', 'Sustainable me', 'Sea Explorers', 'Make & Bake'),
  ('maple-bear-pacaembu', '2º ano', 'Here comes the sun', 'Ancient Civilization', 'Backyard Critters'),
  ('maple-bear-pacaembu', '3º ano', 'Weather Craft', 'Can you hear me?', 'Blowing bubbles'),
  ('maple-bear-pacaembu', '4º ano', 'Around the world', 'Sea Explorers', 'All Aboard'),
  ('maple-bear-pacaembu', '5º ano', 'Sustainable me', 'Make & Bake', 'Cinemaker'),
  ('maple-bear-pacaembu', '6º ano', 'Fly away', 'Light, camera, action!', 'Gaining control'),
  ('maple-bear-pacaembu', '7º ano', 'Modern Times', 'Storybot', 'Time after Time'),
  ('maple-bear-pacaembu', '8º ano', 'Hitmaker', 'Game Designers', 'Enigmaker'),
  ('maple-bear-pacaembu', '9º ano', 'Bright Ideas', 'Lend a hand', 'A-Droid')
ON CONFLICT (escola_id, serie) DO UPDATE SET envio_1 = EXCLUDED.envio_1, envio_2 = EXCLUDED.envio_2, envio_3 = EXCLUDED.envio_3;
